# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Zerocracy
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/**'
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
Style/GlobalVars:
  Enabled: false
Lint/NestedMethodDefinition:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 25
Metrics/PerceivedComplexity:
  Max: 30
Metrics/ClassLength:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 2
Layout/EndOfLine:
  EnforcedStyle: lf
Security/MarshalLoad:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Layout/MultilineAssignmentLayout:
  Enabled: true
Naming/FileName:
  Enabled: false
require:
  - rubocop-rake
  - rubocop-minitest
